
project_id = "tuevghmlxosxuszxjral"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54323
tenant = "realtime"
max_concurrent_users = 200

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"
image_transformation = true

[auth]
enabled = true
port = 54326
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://tuevghmlxosxuszxjral.supabase.co/auth/v1/callback"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
secure_session_cookie = false
persistent_session_cookie = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = false
enable_confirmations = false
template = "Your code is {{ .Code }} ."

[functions.generate-api-key]
verify_jwt = true

[functions.api-auth]
verify_jwt = false

[functions.rate-limiter]
verify_jwt = false

[functions.usage-tracker]
verify_jwt = false

[functions.api-devices]
verify_jwt = false

[functions.api-data]
verify_jwt = false

[functions.api-products]
verify_jwt = false

[functions.webhook-manager]
verify_jwt = false

[functions.webhook-dispatcher]
verify_jwt = false

[functions.api-gateway]
verify_jwt = false

[functions.api-key-management]
verify_jwt = true

[edge_runtime]
enabled = true
port = 54327
inspector_port = 54328

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"
