
project_id = "tuevghmlxosxuszxjral"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[functions.trigger-endpoint]
verify_jwt = true
