// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tuevghmlxosxuszxjral.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1ZXZnaG1seG9zeHVzenhqcmFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMjAxNjgsImV4cCI6MjA1OTg5NjE2OH0.1-ObhemhffJuvAwrdyNDFjBt_lnlsuvk4R0VFPHrR5g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);