
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tuevghmlxosxuszxjral.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1ZXZnaG1seG9zeHVzenhqcmFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMjAxNjgsImV4cCI6MjA1OTg5NjE2OH0.1-ObhemhffJuvAwrdyNDFjBt_lnlsuvk4R0VFPHrR5g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a custom typed client to add our custom RPC function definitions
type CustomSupabaseClient = ReturnType<typeof createClient<Database>> & {
  rpc: ReturnType<typeof createClient<Database>>['rpc'] & {
    (
      fn: 'create_property_bypass_rls' | 'update_property_bypass_rls' | 'delete_property_bypass_rls' |
          'create_device_bypass_rls' | 'update_device_bypass_rls' | 'delete_device_bypass_rls' |
          'get_user_organization_role_bypass_rls' | 'get_organization_members_bypass_rls' |
          'is_org_admin_or_owner_bypass_rls' | 'is_org_member_bypass_rls' |
          'update_product_bypass_rls' | 'get_device_by_id_bypass_rls' |
          'can_access_device' | 'create_audit_log_entry' | 'get_audit_logs',
      params: Record<string, any>
    ): any;
  }
};

const client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
export const supabase = client as CustomSupabaseClient;
